apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgpd-auth-api
  namespace: lgpd-auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lgpd-auth-api
  template:
    metadata:
      labels:
        app: lgpd-auth-api
    spec:
      containers:
        - name: lgpd-auth-api
          # Troque pela imagem publicada no seu registry, ex:
          # ghcr.io/pablovictorsantos01-crypto/lgpd-auth-api:latest
          image: lgpd-auth-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: lgpd-auth-api
  namespace: lgpd-auth-api
spec:
  type: NodePort
  selector:
    app: lgpd-auth-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
